server:
  port: 8444
logging:
  file: /java/OCP_LOGS/ocp-fis/ocp-fis.log
info:
  component: Omnibus Care Plan - FHIR Integration Service
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
ocp-fis:
  fhir:
    serverUrl: http://ocp.consent2share.org/fhir/baseDstu3
    clientSocketTimeoutInMs: 768000
    encoding: json
    defaultResourceBundlePageSize: 10
  ResourceSinglePageLimit: 100
  defaultOrganization: 902
  defaultPractitioner: 1961
  defaultEndPeriod: 20
  defaultMaxDuration: 10
  activityDefinition:
    version: 1.1.0
    pagination:
      default-size: 20
  appointment:
    pagination:
      default-size: 20
  communication:
    pagination:
      default-size: 20
  consent:
    identifier-system: https://bhits.github.io/consent2share/
    codeSystem: http://hl7.org/fhir/v3/ActCode
    pagination:
      default-size: 20
  location:
    pagination:
      default-size: 20
  practitioner:
    pagination:
      default-size: 20
  organization:
    pagination:
      default-size: 20
  patient:
    pagination:
      default-size: 20
  healthcareService:
    pagination:
      default-size: 20
  relatedPerson:
    pagination:
      default-size: 20
  careTeam:
    pagination:
      default-size: 20
  pdf:
    pdfConfigs:
      - type: consent-pdf
        title: Consent to Share My Health Information
        pdFont: TIMES_ROMAN
        pdfPageSize: LETTER
      - type: consent-revocation-pdf
        title: Revocation of Consent to Share My Health Information
        pdFont: TIMES_ROMAN
        pdfPageSize: LETTER
---
# updates configuration for docker environment
spring.profiles: docker
ocp-fis:
  fhir:
    serverUrl: http://fhirtest.uhn.ca/baseDstu3