server:
  port: 8444
logging:
  file: /java/OCP_LOGS/ocp-fis/ocp-fis.log
info:
  component: Omni Care Plan - FHIR Integration Service
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
ocp-fis:
  fhir:
    publish:
      serverUrl:
        resource: http://fhirtest.uhn.ca/baseDstu3
      clientSocketTimeoutInMs: 768000
      encoding: json
---
# updates configuration for docker environment
spring.profiles: docker
ocp-fis:
  fhir:
    publish:
      serverUrl:
        resource: http://hapi-fhir.ocpfis.com:8080/hapi-fhir-jpaserver/baseDstu3