server:
  port: 8444
logging:
  file: /java/OCP_LOGS/ocp-fis/ocp-fis.log
info:
  component: Omnibus Care Plan - FHIR Integration Service
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
ocp-fis:
  fhir:
    serverUrl: http://ocp.consent2share.org/fhir/baseDstu3
    clientSocketTimeoutInMs: 768000
    encoding: json
  location:
    pagination:
      default-size: 20
  practitioner:
    pagination:
      default-size: 20
  organization:
    pagination:
      default-size: 20
  patient:
    pagination:
      default-size: 20
  healthCareService:
    pagination:
      default-size: 20
---
# updates configuration for docker environment
spring.profiles: docker
ocp-fis:
  fhir:
    serverUrl: http://fhirtest.uhn.ca/baseDstu3